version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: monthly
    day: tuesday
    time: "01:00"
  cooldown:
    default-days: 14

- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: monthly
    day: tuesday
    time: "01:00"
  cooldown:
    default-days: 14
