services:
  app:
    image: dockershelf/dockershelf:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    volumes:
      - .:/home/dockershelf/app
      - ~/Library/Caches/pip:/home/dockershelf/.cache/pip
