[tox]
envlist = lint, format, coverage

[testenv:lint]
skip_install = True
setenv =
    PYTHONPATH = {toxinidir}
deps =
    -r{toxinidir}/requirements-dev.txt
commands =
    ruff format --check scripts update.py tests
    ruff check scripts update.py tests
    bandit -c {toxinidir}/pyproject.toml -r update.py
    pyright scripts update.py

[testenv:format]
skip_install = True
deps =
    -r{toxinidir}/requirements-dev.txt
commands =
    ruff format scripts update.py tests
    ruff check --fix --select F401,F841,I001 scripts update.py tests

[testenv:coverage]
skip_install = True
setenv =
    PYTHONPATH = {toxinidir}
deps =
    -r{toxinidir}/requirements.txt
    -r{toxinidir}/requirements-dev.txt
commands =
    coverage run --source scripts -m unittest discover -s tests -v
    coverage report -m
