[tox]
envlist = lint, format, coverage

[flake8]
max-line-length = 120
max-complexity = 13

[testenv:lint]
skip_install = True
deps =
    flake8
commands =
    flake8 scripts update.py tests

[testenv:format]
skip_install = True
deps =
    -r{toxinidir}/requirements-dev.txt
commands =
    autoflake --check --recursive --remove-all-unused-imports --remove-unused-variables --ignore-init-module-imports scripts update.py tests
    autopep8 --diff --recursive --aggressive --aggressive scripts update.py tests

[testenv:coverage]
skip_install = True
setenv =
    PYTHONPATH = {toxinidir}
deps =
    coverage
    packaging==26.2
commands =
    coverage run --source scripts -m unittest discover -s tests -v
    coverage report -m
