FROM luisalejandro/debian-amd64:sid

RUN apt-get update && apt-get install -y --no-install-recommends \
		python-pip \
		python-setuptools \
		python3-pip \
		python3-setuptools \
	&& rm -rf /var/lib/apt/lists/*

