name: Code Quality

on:
  pull_request:
    types:
      - opened
      - ready_for_review
      - synchronize
      - reopened
    branches:
      - develop

permissions:
  contents: read

jobs:
  code-quality:
    name: Code Quality
    runs-on: ubuntu-24.04
    container:
      image: semgrep/semgrep
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Semgrep scan
        run: |
          semgrep scan \
            --config p/ci \
            --config p/python \
            --baseline-commit "${{ github.event.pull_request.base.sha }}" \
            --metrics=off \
            --error
