name: Trigger (develop branch)

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        include:
          # - docker-image-name: "dockershelf/debian:bullseye"
          #   docker-image-extra-tags: "dockershelf/debian:oldstable"
          #   debian-suite: "oldstable"
          # - docker-image-name: "dockershelf/debian:bookworm"
          #   docker-image-extra-tags: "dockershelf/debian:stable"
          #   debian-suite: "stable"
          # - docker-image-name: "dockershelf/debian:trixie"
          #   docker-image-extra-tags: "dockershelf/debian:testing"
          #   debian-suite: "testing"
          # - docker-image-name: "dockershelf/debian:sid"
          #   docker-image-extra-tags: "dockershelf/debian:unstable dockershelf/debian:latest"
          #   debian-suite: "unstable"
          # - docker-image-name: "dockershelf/latex:basic"
          #   docker-image-extra-tags: "dockershelf/latex:latest"
          # - docker-image-name: "dockershelf/latex:full"
          # - docker-image-name: "dockershelf/python:3.7-bookworm"
          #   docker-image-extra-tags: "dockershelf/python:3.7-stable"
          # - docker-image-name: "dockershelf/python:3.7-sid"
          #   docker-image-extra-tags: "dockershelf/python:3.7-unstable dockershelf/python:3.7"
          # - docker-image-name: "dockershelf/python:3.10-bookworm"
          #   docker-image-extra-tags: "dockershelf/python:3.10-stable"
          # - docker-image-name: "dockershelf/python:3.10-sid"
          #   docker-image-extra-tags: "dockershelf/python:3.10-unstable dockershelf/python:3.10"
          - docker-image-name: "dockershelf/python:3.11-bookworm"
            docker-image-extra-tags: "dockershelf/python:3.11-stable"
          - docker-image-name: "dockershelf/python:3.11-sid"
            docker-image-extra-tags: "dockershelf/python:3.11-unstable dockershelf/python:3.11"
          - docker-image-name: "dockershelf/python:3.12-bookworm"
            docker-image-extra-tags: "dockershelf/python:3.12-stable dockershelf/python:3-stable dockershelf/python:3-bookworm dockershelf/python:latest-stable dockershelf/python:latest-bookworm"
          - docker-image-name: "dockershelf/python:3.12-sid"
          #   docker-image-extra-tags: "dockershelf/python:3.12-unstable dockershelf/python:3.12 dockershelf/python:3-unstable dockershelf/python:3-sid dockershelf/python:3 dockershelf/python:latest-unstable dockershelf/python:latest-sid dockershelf/python:latest"
          # - docker-image-name: "dockershelf/node:12-bookworm"
          #   docker-image-extra-tags: "dockershelf/node:12-stable"
          # - docker-image-name: "dockershelf/node:12-sid"
          #   docker-image-extra-tags: "dockershelf/node:12-unstable dockershelf/node:12"
          # - docker-image-name: "dockershelf/node:14-bookworm"
          #   docker-image-extra-tags: "dockershelf/node:14-stable"
          # - docker-image-name: "dockershelf/node:14-sid"
          #   docker-image-extra-tags: "dockershelf/node:14-unstable dockershelf/node:14"
          # - docker-image-name: "dockershelf/node:16-bookworm"
          #   docker-image-extra-tags: "dockershelf/node:16-stable"
          # - docker-image-name: "dockershelf/node:16-sid"
          #   docker-image-extra-tags: "dockershelf/node:16-unstable dockershelf/node:16"
          # - docker-image-name: "dockershelf/node:18-bookworm"
          #   docker-image-extra-tags: "dockershelf/node:18-stable"
          # - docker-image-name: "dockershelf/node:18-sid"
          #   docker-image-extra-tags: "dockershelf/node:18-unstable dockershelf/node:18"
          # - docker-image-name: "dockershelf/node:20-bookworm"
          #   docker-image-extra-tags: "dockershelf/node:20-stable dockershelf/node:latest-stable dockershelf/node:latest-bookworm"
          # - docker-image-name: "dockershelf/node:20-sid"
          #   docker-image-extra-tags: "dockershelf/node:20-unstable dockershelf/node:20 dockershelf/node:latest-unstable dockershelf/node:latest-sid dockershelf/node:latest"
          # - docker-image-name: "dockershelf/go:1.19-bookworm"
          #   docker-image-extra-tags: "dockershelf/go:1.19-stable"
          # - docker-image-name: "dockershelf/go:1.19-sid"
          #   docker-image-extra-tags: "dockershelf/go:1.19-unstable dockershelf/go:1.19"
          # - docker-image-name: "dockershelf/go:1.20-bookworm"
          #   docker-image-extra-tags: "dockershelf/go:1.20-stable"
          # - docker-image-name: "dockershelf/go:1.20-sid"
          #   docker-image-extra-tags: "dockershelf/go:1.20-unstable dockershelf/go:1.20"
          # - docker-image-name: "dockershelf/go:1.21-bookworm"
          #   docker-image-extra-tags: "dockershelf/go:1.21-stable"
          # - docker-image-name: "dockershelf/go:1.21-sid"
          #   docker-image-extra-tags: "dockershelf/go:1.21-unstable dockershelf/go:1.21"
          # - docker-image-name: "dockershelf/go:1.22-bookworm"
          #   docker-image-extra-tags: "dockershelf/go:1.22-stable dockershelf/go:latest-stable dockershelf/go:latest-bookworm"
          # - docker-image-name: "dockershelf/go:1.22-sid"
          #   docker-image-extra-tags: "dockershelf/go:1.22-unstable dockershelf/go:1.22 dockershelf/go:latest-unstable dockershelf/go:latest-sid dockershelf/go:latest"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: develop
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1"
          bundler-cache: true

      - name: Building docker image
        env:
          DOCKER_IMAGE_NAME: ${{ matrix.docker-image-name }}
          DEBIAN_SUITE: ${{ matrix.debian-suite }}
          DH_USERNAME: ${{ secrets.DH_USERNAME }}
          DH_PASSWORD: ${{ secrets.DH_PASSWORD }}
        run: |
          bash build-image.sh "${DOCKER_IMAGE_NAME}" "${DEBIAN_SUITE}" "${DH_USERNAME}" "${DH_PASSWORD}" "develop"

      - name: Testing docker image
        env:
          DOCKER_IMAGE_NAME: ${{ matrix.docker-image-name }}
          DOCKER_IMAGE_EXTRA_TAGS: ${{ matrix.docker-image-extra-tags }}
        run: |
          bash test-image.sh "${DOCKER_IMAGE_NAME}" "develop"

      - name: Pushing docker image
        env:
          DOCKER_IMAGE_NAME: ${{ matrix.docker-image-name }}
          DOCKER_IMAGE_EXTRA_TAGS: ${{ matrix.docker-image-extra-tags }}
          DH_USERNAME: ${{ secrets.DH_USERNAME }}
          DH_PASSWORD: ${{ secrets.DH_PASSWORD }}
        run: |
          bash push-image.sh "${DOCKER_IMAGE_NAME}" "${DH_USERNAME}" "${DH_PASSWORD}" "${DOCKER_IMAGE_EXTRA_TAGS}" "develop"
